### ISSUE TITLE
javascript error thrown in status.js

### ISSUE THREAD

**Issue by mcoughli** [ewust/jscan#10]
/static/status.js:132: Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

I assume this has to do with removing the iframes at some point?

**Comment by ewust** [comment]
This usually means removeProgress() (or removeStatus(), but this case suggests the former) was called with a key that doesn't exist; either removeStatus() was called before, or maybe the ID passed to removeProgress was never created.

When does this occur during a scan?

**Comment by mcoughli** [comment]
i think that one occurs right at the beginning and then right at the end. there don't seem to be many that occur in the middle of the scan

**Comment by ewust** [comment]
This has been fixed by getting rid of a race condition between updateStatus() and removeProgress() (and a subsequent race between updateStatus() and updateStatus()).
