### ISSUE TITLE
Figure out a better way to deal with periods in IPs/domain names

### ISSUE THREAD

**Issue by ewust** [ewust/jscan#2]
Mongo doesn't allow key names to have periods (or $) in them, so we are currently escaping by replacing with an underscore. This might cause problems for domains that have underscores in them; we should find a better way to deal with this in general, perhaps by using their full-Unicode equivalents, or maybe moving away from MongoDB entirely.

**Comment by mcoughli** [comment]
using base64 encoding to store the rebind urls and ip addresses. the internet suggested this as a possible solution. just need to remember that these keys are base64 encoded
