### ISSUE TITLE
Scan complete logic bug

### ISSUE THREAD

**Issue by ewust** [ewust/jscan#6]
After a scan is completed, if the user goes back to the scan page, and tries to start a new scan, it will scan for IP/ports, but when sending the results to the scanner_endpoint, it gets a "Scanning complete" response from the server (which throws an error we don't handle in parallel-scanner.js).

Not sure why this happens sometimes, but not others?

**Comment by mcoughli** [comment]
got rid of the situation where this occurs. if scanning is complete, the endpoint will still process the data rather then send the response that it is finished. instead, the scanning page checks if scanning has been completed when loading and creates a new session
